title               : VS Mokeeth
description         : >-                               # >- means to ignore newlines until "url:"
                      Result oriented and goal driven individual with deep interests in finance and various technologies.
url                 : "https://vyshnav2255.github.io/Minimal-Portfolio-Website/"
repository          : Vyshnav2255/Minimal-Portfolio-Website 

email: 2006291@kiit.ac.in
github_user: VS-Mokeeth
instagram: /
twitter: /


exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock